<?php



if (!defined('IN_DISCUZ')) {

	exit('Access Denied');

}



$c1lang = array (

	'register' => '注册',
	'qqlogin' => 'QQ登录',
	'wxlogin' => '微信',
	'email_1' => '已验证邮箱',
	'email_0' => '未验证邮箱',
	'bindqq_1' => '已绑定QQ',
	'bindqq_0' => '未绑定QQ',
	'user_lv' => '等级',
	'mypost' => '我的帖子',
	'upload_avatar' => '上传头像',
	'modify_avatar' => '修改头像',
	'myfavorite' => '我的收藏',
	'my_friends' => '我的好友',
	'modify_data' => '修改资料',
	'logout' => '注销登录',
	'tz_modmenu' => '管理',
	'tz_reply' => '小说创作区新帖',
	'tz_new' => '讨论交流区新帖',
	'tz_hot' => '漫画与游戏区新帖',
    'tz_jinghua' => '精华推荐',
    'tz_book' => '书城更新',
	'tz_digest' => '最新回复',
	'tz_author' => '楼主',
	'tz_lastreply' => '最后发表',
	'tz_icon_zd' => '顶',
	'tz_icon_zdes' => '含置顶属性',
	'tz_icon_jh' => '精',
	'tz_icon_jhes' => '精华',
	'tz_icon_tp' => '图',
	'tz_icon_tpes' => '内含图片',
	'tz_icon_fj' => '附',
	'tz_icon_fjes' => '内含附件',
	'post' => '发布',
	'catlist' => '版块列表',
	'mn_news' => '资讯动态',
	'mn_pics' => '萌图展区',
	'mn_reg' => '新会员',
	'mn_post' => '我要发帖',
	'fm_post' => '本版发帖',
	'no_reply' => '暂无发帖',
	'no_tag' => '无标签',
	'today_hot' => '今日热点',
	'forum_subforums' => '子版',
	'index_posts' => '总帖',
	'index_threads' => '主题',
	'index_replies' => '回帖',
	'description' => '简介',
	'notag' => '没有可用标签',
	'tagcount' => '个主题',
	'lastreplies' => '最新评论',
	'lastrepliescount' => '条最新评论',
	'from' => '来自',
	'hot_rec' => '热点推荐',
	'rank' => '排行',
	'day_rank' => '日排行',
	'week_rank' => '周排行',
	'month_rank' => '月排行',
	'app' => 'APP',
	'wx' => '交流群',
	'reply' => '回复',
	'list' => '列表',
	'forum' => '论坛',
	'return_list' => '返回列表',
	'return_forum' => '返回论坛',
	'go_top' => 'TOP',
	'kefu' => 'QQ交流群',
	'c_download' => '扫描下载',
	'c_focus' => '扫描加入交流群',
	'app_ios' => '暂无IOS端',
	'app_android' => '安卓端',
	'kf_cp_dec' => '加群时间<br/>16:00~21:00',
	'kefu_qq' => '邮件反馈',
	'kefu_qq_1' => '617588104',
	'kefu_qq_2' => '617588104',
	'kefu_qq_3' => '617588104',
	'kefu_email_1' => 'admin@.com',
	'kefu_email_2' => 'admin@.com',
	'join_moderator' => '<a href="#" target="_blank">暂无版主, +申请版主.</a>',
	'copyright' => 'Created & Modified by acgi.'
);


