<?php

if (!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$c1lang = array (
	'register' => '注冊',
	'qqlogin' => 'QQ登錄',
	'wxlogin' => '微信',
	'email_1' => '已驗證郵箱',
	'email_0' => '未驗證郵箱',
	'bindqq_1' => '已綁定QQ',
	'bindqq_0' => '未綁定QQ',
	'user_lv' => '等級',
	'mypost' => '我的帖子',
	'upload_avatar' => '上傳頭像',
	'modify_avatar' => '修改頭像',
	'myfavorite' => '我的收藏',
	'my_friends' => '我的好友',
	'modify_data' => '修改資料',
	'logout' => '注銷登錄',
	'tz_modmenu' => '管理',
	'tz_reply' => '最新回復',
	'tz_new' => '最新主題',
	'tz_hot' => '熱門主題',
	'tz_digest' => '精華推薦',
	'tz_author' => '樓主',
	'tz_lastreply' => '最后發表',
	'tz_icon_zd' => '頂',
	'tz_icon_zdes' => '含置頂屬性',
	'tz_icon_jh' => '精',
	'tz_icon_jhes' => '精華',
	'tz_icon_tp' => '圖',
	'tz_icon_tpes' => '內含圖片',
	'tz_icon_fj' => '附',
	'tz_icon_fjes' => '內含附件',
	'post' => '發布',
	'catlist' => '版塊列表',
	'mn_news' => '資訊動態',
	'mn_pics' => '萌圖展區',
	'mn_reg' => '新會員',
	'mn_post' => '我要發帖',
	'fm_post' => '本版發帖',
	'no_reply' => '暫無發帖',
	'no_tag' => '無標簽',
	'today_hot' => '今日熱點',
	'forum_subforums' => '子版',
	'index_posts' => '總帖',
	'index_threads' => '主題',
	'index_replies' => '回帖',
	'description' => '簡介',
	'notag' => '沒有可用標簽',
	'tagcount' => '個主題',
	'lastreplies' => '最新評論',
	'lastrepliescount' => '條最新評論',
	'from' => '來自',
	'hot_rec' => '熱點推薦',
	'rank' => '排行',
	'day_rank' => '日排行',
	'week_rank' => '周排行',
	'month_rank' => '月排行',
	'app' => 'APP',
	'wx' => '微信',
	'reply' => '回復',
	'list' => '列表',
	'forum' => '論壇',
	'return_list' => '返回列表',
	'return_forum' => '返回論壇',
	'go_top' => 'TOP',
	'kefu' => '客服',
	'c_download' => '掃描下載',
	'c_focus' => '掃描關注公眾號',
	'app_ios' => 'IOS端',
	'app_android' => '安卓端',
	'kf_cp_dec' => '工作時間<br/>08:00~17:00',
	'kefu_qq' => '客服QQ',
	'kefu_qq_1' => '66666666',
	'kefu_qq_2' => '88888888',
	'kefu_qq_3' => '99999999',
	'kefu_email_1' => 'e-mail01@gmail.com',
	'kefu_email_2' => 'e-mail02@gmail.com',
	'join_moderator' => '<a href="#" target="_blank">暫無版主, +申請版主.</a>',
	'copyright' => 'Created & Modified by acgi.'
);

